apiVersion: configsync.gke.io/v1beta1
kind: RootSync
metadata:
  name: nephio-workload-cluster-sync
  namespace: config-management-system
  annotations:
    config.kubernetes.io/depends-on: apiextensions.k8s.io/CustomResourceDefinition/rootsyncs.configsync.gke.io
spec:
  sourceFormat: unstructured
  git:
    repo: http://gitea:3000/nephio/nephio-configsync
    branch: main
    auth: none
